---
name: Ex. 5 - Error Handling
order: 5
---

# Ex. 5 - Error Handling

## Instructions

Currently our application does not handle error cases. When using an external API, we do not control it and we must always expect to have errors.

We will use the [Error Boundaries](https://reactjs.org/docs/error-boundaries.html), with this technique, we will be both tolerant of errors from the API but also to those from our own code.

- Create a simple `ErrorBoundary` in `src/components/Catch.js`
- Wrap the entire application with the `Catch` component in `index.js`
- Modify the custom `useMovieSearch` Hook to issue an error when the request fails

### Expected result

When the search field is empty, I have an error message.

<iframe
  src="https://codesandbox.io/embed/github/smooth-code/react-hooks-workshop/tree/end-exercise-5/?fontsize=14&view=preview"
  style={{
    width: '100%',
    height: 500,
    border: 0,
    borderRadius: 4,
    overflow: 'hidden',
  }}
  sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin"
/>

## Help

### Error Boundary: implementation

```js
import React, { Component } from 'react'

export default class Catch extends Component {
  state = { hasError: false }

  static getDerivedStateFromError(error) {
    // Update the state, at the next rendering, we'll know that an error has been caught
    return { hasError: true }
  }

  render () {
    if (this.state.hasError) {
      // Display of the fallback of our choice
      return <h1>Something went wrong.</h1>
    }

    return this.props.children
  }
}
```

### How do you the error bondary?

```js
ReactDOM.render(
  <Catch>
    <App />
  </Catch>
  document.getElementById('root'),
)
```

### How should I throw the error?

```js
import { useState, useEffect } from 'react'

function useApi () {
  // State containing the result
  const [state, setState] = useState({ result: null, error: null })

  useEffect(() => {
    request()
      // When everything goes well, I get a result
      .then(result => setState({ result, error: null }))
      // In case of error, the catch is called
      .catch(error => setState({ error, result: null }))
  })

  // If an error has been returned by the query, then I throw
  if (state.error) {
    throw state.error
  }

  return state.result
}
```
